# Generated by Django 6.0.4 on 2026-04-20 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0006_department_employmenttype_enterprise_systemrole_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Maintenance', 'Maintenance')], default='Ongoing', max_length=20)),
                ('infrastructure', models.JSONField(blank=True, default=dict)),
                ('links', models.JSONField(blank=True, default=list)),
                ('documents', models.JSONField(blank=True, default=list)),
                ('stack', models.JSONField(blank=True, default=list)),
                ('additions', models.JSONField(blank=True, default=list)),
                ('expected_publish', models.DateField(blank=True, null=True)),
                ('testing_date', models.DateField(blank=True, null=True)),
                ('frontend_finish_date', models.DateField(blank=True, null=True)),
                ('backend_finish_date', models.DateField(blank=True, null=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='employees.enterprise')),
                ('project_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to='employees.employee')),
                ('team_members', models.ManyToManyField(blank=True, related_name='assigned_projects', to='employees.employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
