# Generated by Django 6.0.4 on 2026-04-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employeerole_reported_to'),
        ('projects', '0002_remove_project_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='qa_testers',
            field=models.ManyToManyField(blank=True, related_name='tested_projects', to='employees.employee'),
        ),
    ]
