# Generated by Django 6.0.4 on 2026-04-25 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employeerole_is_primary'),
        ('projects', '0005_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='VPS', max_length=50)),
                ('maintained_by', models.CharField(blank=True, max_length=255, null=True)),
                ('root_address', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('a_record', models.CharField(blank=True, max_length=255, null=True)),
                ('aaaa_record', models.CharField(blank=True, max_length=255, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('alert_date', models.DateField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('which_mail', models.CharField(blank=True, max_length=255, null=True)),
                ('mail_password', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Offline', 'Offline'), ('Scaling', 'Scaling'), ('Decommissioned', 'Decommissioned')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='employees.enterprise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
