# Generated by Django 6.0.4 on 2026-04-25 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employeerole_is_primary'),
        ('projects', '0006_server'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('enterprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='employees.enterprise')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
