# Generated by Django 6.0.4 on 2026-04-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarding_poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
