# Generated by Django 6.0.4 on 2026-04-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_onboarding_poster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='aadhaar_card_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='github_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='linkedin_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='onboarding_poster_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan_card_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photograph_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='portfolio_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
