# Generated by Django 6.0.4 on 2026-04-21 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_department_employmenttype_enterprise_systemrole_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeerole',
            name='reported_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee'),
        ),
    ]
