# Generated by Django 6.0.4 on 2026-04-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employeerole_reported_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerole',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
