# Generated by Django 6.0.4 on 2026-04-25 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employeerole_is_primary'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reimbursements', to='employees.enterprise'),
        ),
    ]
