# Generated by Django 6.0.4 on 2026-04-25 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employeerole_is_primary'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='employees.enterprise'),
        ),
        migrations.AddField(
            model_name='keyperformancescore',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kps', to='employees.enterprise'),
        ),
        migrations.AddField(
            model_name='keyresultindicator',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kri', to='employees.enterprise'),
        ),
        migrations.AddField(
            model_name='performancesnapshot',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to='employees.enterprise'),
        ),
    ]
