# Generated by Django 6.0.4 on 2026-04-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('max_days', models.IntegerField(default=12)),
                ('is_paid', models.BooleanField(default=True)),
                ('color', models.CharField(default='#10b981', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
