# Generated by Django 6.0.4 on 2026-04-23 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_employeerole_reported_to'),
        ('leaves', '0002_leavecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavecategory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='leave_type',
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='leave_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaves.leavecategory'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_category')},
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaves.leavecategory'),
        ),
        migrations.RemoveField(
            model_name='leavebalance',
            name='leave_type',
        ),
    ]
