# Generated by Django 6.0.4 on 2026-04-25 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employeerole_is_primary'),
        ('leaves', '0003_alter_leavebalance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.enterprise'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.enterprise'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('employee', 'leave_category', 'enterprise')},
        ),
    ]
