# Generated by Django 6.0.4 on 2026-04-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('employees', '0005_alter_employee_aadhaar_card_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', '-check_in']},
        ),
        migrations.AddField(
            model_name='attendancebreak',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='completed_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='planned_work',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Break', 'Break'), ('Clocked Out', 'Clocked Out'), ('Late', 'Late'), ('Absent', 'Absent')], default='Present', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='total_break_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='total_hours',
            field=models.CharField(default='0h 0m', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('employee', 'date')},
        ),
    ]
