# Generated by Django 6.0.4 on 2026-04-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='overtime_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='overtime_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='requested_extra_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
