# Generated by Django 6.0.4 on 2026-04-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='report_status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Delayed', 'Delayed'), ('On Hold', 'On Hold')], default='In Progress', max_length=20),
        ),
    ]
