# Generated by Django 6.0.4 on 2026-04-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancerecord_report_status'),
        ('projects', '0004_project_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='attendance_records', to='projects.project'),
        ),
    ]
